# Payment Service specific configuration
# This file contains configuration specific to the payment service

# Payment processing settings
payment_processing:
  supported_currencies: ["USD", "EUR", "GBP", "CAD", "AUD"]
  default_currency: "USD"

  transaction_limits:
    min_amount: 0.50
    max_amount_per_transaction: 10000.00
    max_amount_per_day: 50000.00
    max_transactions_per_day: 100

  fees:
    processing_fee_percent: 2.9
    fixed_fee_cents: 30
    international_fee_percent: 1.5
    currency_conversion_fee_percent: 1.0

# Payment gateway configurations
payment_gateways:
  stripe:
    enabled: true
    api_key: "${STRIPE_SECRET_KEY}"
    webhook_secret: "${STRIPE_WEBHOOK_SECRET}"
    api_version: "2023-10-16"
    timeout_seconds: 30

  paypal:
    enabled: true
    client_id: "${PAYPAL_CLIENT_ID}"
    client_secret: "${PAYPAL_CLIENT_SECRET}"
    sandbox_mode: "${PAYPAL_SANDBOX_MODE:-true}"
    timeout_seconds: 45

  square:
    enabled: false
    application_id: "${SQUARE_APPLICATION_ID}"
    access_token: "${SQUARE_ACCESS_TOKEN}"
    sandbox_mode: "${SQUARE_SANDBOX_MODE:-true}"

# Security and compliance
security:
  pci_compliance:
    level: "Level 1"
    tokenization_enabled: true
    encryption_standard: "AES-256"
    key_rotation_days: 30

  fraud_detection:
    enabled: true
    risk_threshold: 0.8
    velocity_checks: true
    geolocation_checks: true
    device_fingerprinting: true
    ml_model_enabled: true

  data_protection:
    mask_card_numbers: true
    log_sensitive_data: false
    data_retention_days: 2555  # 7 years for compliance
    secure_deletion: true

# Transaction processing
transaction_processing:
  retry_policy:
    max_attempts: 3
    backoff_multiplier: 2.0
    max_delay_seconds: 30
    retryable_errors: ["network_error", "gateway_timeout"]

  timeout_settings:
    authorization_timeout: 10
    capture_timeout: 30
    refund_timeout: 60
    void_timeout: 15

  batch_processing:
    enabled: true
    batch_size: 100
    processing_interval_minutes: 15
    max_batch_age_hours: 2

# Webhook management
webhooks:
  enabled: true
  retry_attempts: 5
  retry_delay_seconds: [1, 5, 25, 125, 625]
  timeout_seconds: 10
  signature_verification: true

  endpoints:
    payment_succeeded: "/webhooks/payment/succeeded"
    payment_failed: "/webhooks/payment/failed"
    refund_processed: "/webhooks/refund/processed"
    chargeback_created: "/webhooks/chargeback/created"

# Reporting and analytics
reporting:
  daily_reports: true
  weekly_reports: true
  monthly_reports: true

  metrics:
    track_success_rate: true
    track_average_amount: true
    track_processing_time: true
    track_failure_reasons: true

  export_formats: ["csv", "json", "pdf"]
  retention_months: 84  # 7 years

# Integration settings
integrations:
  accounting:
    enabled: true
    sync_frequency_hours: 1
    chart_of_accounts_mapping: true

  tax_calculation:
    enabled: true
    provider: "avalara"
    real_time_calculation: true

  notification_service:
    enabled: true
    send_payment_confirmations: true
    send_failure_notifications: true
    send_refund_notifications: true

# Monitoring and alerting
monitoring:
  alert_conditions:
    high_failure_rate_threshold: 0.05  # 5%
    high_processing_time_threshold: 5000  # 5 seconds
    suspicious_activity_threshold: 10  # transactions per minute

  custom_metrics:
    - "payment_success_rate"
    - "average_processing_time"
    - "fraud_detection_rate"
    - "chargeback_rate"
    - "revenue_per_hour"

# Backup and disaster recovery
backup:
  enabled: true
  frequency_hours: 1
  retention_days: 90
  encryption_enabled: true
  cross_region_replication: true

  disaster_recovery:
    rto_minutes: 15  # Recovery Time Objective
    rpo_minutes: 5   # Recovery Point Objective
    failover_enabled: true
