# User Service specific configuration
# This file contains configuration specific to the user service

# User service specific settings
user_management:
  password_policy:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    max_age_days: 90
    history_count: 5

  account_settings:
    max_login_attempts: 5
    lockout_duration_minutes: 30
    session_timeout_minutes: 60
    require_email_verification: true
    allow_social_login: true

  profile_settings:
    max_profile_image_size_mb: 5
    allowed_image_formats: ["jpg", "jpeg", "png", "webp"]
    profile_completion_required: false

# Authentication specific settings
authentication:
  jwt:
    access_token_expiry_minutes: 15
    refresh_token_expiry_days: 30
    allow_token_refresh: true
    max_refresh_count: 10

  oauth:
    providers:
      google:
        enabled: true
        client_id: "${GOOGLE_CLIENT_ID}"
        client_secret: "${GOOGLE_CLIENT_SECRET}"
        scope: "email profile"

      github:
        enabled: true
        client_id: "${GITHUB_CLIENT_ID}"
        client_secret: "${GITHUB_CLIENT_SECRET}"
        scope: "user:email"

  api_keys:
    enabled: true
    max_keys_per_user: 5
    default_expiry_days: 365
    allow_scoped_keys: true

# User data management
data_management:
  gdpr_compliance:
    enabled: true
    data_retention_days: 2555  # 7 years
    allow_data_export: true
    allow_data_deletion: true
    anonymization_enabled: true

  backup:
    enabled: true
    frequency_hours: 6
    retention_days: 30
    encryption_enabled: true

# Rate limiting specific to user operations
rate_limiting:
  registration:
    requests_per_hour: 10
    requests_per_day: 50

  login:
    requests_per_minute: 5
    requests_per_hour: 100

  password_reset:
    requests_per_hour: 3
    requests_per_day: 10

  profile_update:
    requests_per_minute: 10
    requests_per_hour: 100

# Notification preferences
notifications:
  email:
    welcome_email: true
    password_reset: true
    security_alerts: true
    marketing_emails: false

  sms:
    two_factor_auth: true
    security_alerts: true
    password_reset: false

  push:
    security_alerts: true
    feature_updates: false

# Integration settings
integrations:
  analytics:
    enabled: true
    track_user_events: true
    anonymize_data: true

  monitoring:
    track_performance: true
    alert_on_failures: true
    custom_metrics:
      - "user_registrations_per_hour"
      - "failed_login_attempts"
      - "password_reset_requests"
