# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "order_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13order_service.proto\x12\rorder_service"@\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01"\x91\x01\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\'\n\x05items\x18\x03 \x03(\x0b\x32\x18.order_service.OrderItem\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x05 \x01(\x01\x12\x12\n\ncreated_at\x18\x06 \x01(\x03"R\n\x12\x43reateOrderRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\'\n\x05items\x18\x02 \x03(\x0b\x32\x18.order_service.OrderItem"b\n\x13\x43reateOrderResponse\x12#\n\x05order\x18\x01 \x01(\x0b\x32\x14.order_service.Order\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t"_\n\x10GetOrderResponse\x12#\n\x05order\x18\x01 \x01(\x0b\x32\x14.order_service.Order\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t"\x14\n\x12HealthCheckRequest"\xa6\x01\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12J\n\x0c\x64\x65pendencies\x18\x02 \x03(\x0b\x32\x34.order_service.HealthCheckResponse.DependenciesEntry\x1a\x33\n\x11\x44\x65pendenciesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x87\x02\n\x0cOrderService\x12T\n\x0b\x43reateOrder\x12!.order_service.CreateOrderRequest\x1a".order_service.CreateOrderResponse\x12K\n\x08GetOrder\x12\x1e.order_service.GetOrderRequest\x1a\x1f.order_service.GetOrderResponse\x12T\n\x0bHealthCheck\x12!.order_service.HealthCheckRequest\x1a".order_service.HealthCheckResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "order_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HEALTHCHECKRESPONSE_DEPENDENCIESENTRY"]._loaded_options = None
    _globals["_HEALTHCHECKRESPONSE_DEPENDENCIESENTRY"]._serialized_options = b"8\001"
    _globals["_ORDERITEM"]._serialized_start = 38
    _globals["_ORDERITEM"]._serialized_end = 102
    _globals["_ORDER"]._serialized_start = 105
    _globals["_ORDER"]._serialized_end = 250
    _globals["_CREATEORDERREQUEST"]._serialized_start = 252
    _globals["_CREATEORDERREQUEST"]._serialized_end = 334
    _globals["_CREATEORDERRESPONSE"]._serialized_start = 336
    _globals["_CREATEORDERRESPONSE"]._serialized_end = 434
    _globals["_GETORDERREQUEST"]._serialized_start = 436
    _globals["_GETORDERREQUEST"]._serialized_end = 471
    _globals["_GETORDERRESPONSE"]._serialized_start = 473
    _globals["_GETORDERRESPONSE"]._serialized_end = 568
    _globals["_HEALTHCHECKREQUEST"]._serialized_start = 570
    _globals["_HEALTHCHECKREQUEST"]._serialized_end = 590
    _globals["_HEALTHCHECKRESPONSE"]._serialized_start = 593
    _globals["_HEALTHCHECKRESPONSE"]._serialized_end = 759
    _globals["_HEALTHCHECKRESPONSE_DEPENDENCIESENTRY"]._serialized_start = 708
    _globals["_HEALTHCHECKRESPONSE_DEPENDENCIESENTRY"]._serialized_end = 759
    _globals["_ORDERSERVICE"]._serialized_start = 762
    _globals["_ORDERSERVICE"]._serialized_end = 1025
# @@protoc_insertion_point(module_scope)
