# Logstash Configuration
http.host: "0.0.0.0"
http.port: 9600

# Pipeline settings
pipeline.workers: 4
pipeline.batch.size: 1000
pipeline.batch.delay: 50

# Queue settings
queue.type: persisted
queue.max_bytes: 1gb
queue.checkpoint.writes: 1024

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# JVM settings
pipeline.java_execution: true

# Log level
log.level: info
path.logs: /usr/share/logstash/logs

# Dead letter queue
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1gb

# X-Pack monitoring
xpack.monitoring.enabled: false
