apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    marty.framework/component: observability
    marty.framework/phase: "phase2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: monitoring
spec:
  limits:
  - type: Container
    default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
  - type: PersistentVolumeClaim
    max:
      storage: 100Gi
