apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-order-service
  namespace: default
  labels:
    app: demo-order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-order-service
  template:
    metadata:
      labels:
        app: demo-order-service
    spec:
      containers:
      - name: order-service
        image: demo-order-service:latest
        imagePullPolicy: Never  # Use local image in Kind
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "kubernetes-demo"
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: demo-order-service
  namespace: default
  labels:
    app: demo-order-service
spec:
  selector:
    app: demo-order-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
