# Marty Microservices Framework - Tool Configuration

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "marty-microservices-framework"
version = "1.0.0"
description = "Enterprise-grade microservices framework"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1.6",
    "astroid>=2.15.0",   # For additional code analysis
    "mypy>=1.0.0",       # For static type checking
    "prometheus-client>=0.17.0",  # For metrics collection
    "aiokafka>=0.8.0",           # For Kafka event streaming
    "aiohttp>=3.8.0",            # For HTTP load testing
    "grpcio>=1.50.0",            # For gRPC load testing
    "pydantic>=2.0.0",           # For data validation
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-benchmark>=4.0.0",
    "pytest-html>=4.1.1",
    "playwright>=1.40.0",
    "pytest-playwright>=0.4.3",
    "psutil>=5.9.0",
    "matplotlib>=3.7.0",
    "pandas>=2.0.0",
    "ruff>=0.1.6",
    "mypy>=1.7.0",
    "pre-commit>=3.6.0",
]

# Hatchling build configuration
[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/scripts",
    "/examples",
    "/config",
]

[tool.hatch.build.targets.wheel]
packages = ["src/framework"]

# Marty Microservices Framework - Ruff Configuration
[tool.ruff]
line-length = 88
target-version = "py310"
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "microservice_project_template/.venv",
    "build",
    "dist",
]

# Enable specific rule sets
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "B",    # flake8-bugbear
    "I",    # isort
    "UP",   # pyupgrade
    "N",    # pep8-naming
    "PT",   # flake8-pytest-style
    "RUF",  # ruff-specific rules
]

ignore = [
    "E501",  # line too long (handled by black)
]

[tool.ruff.isort]
known-first-party = ["scripts"]
combine-as-imports = true

[tool.ruff.per-file-ignores]
"scripts/*" = ["T201"]  # Allow print statements in scripts
"microservice_project_template/**" = ["ALL"]  # Ignore project template

[dependency-groups]
dev = [
    "jinja2>=3.1.6",
    "mypy>=1.18.2",
]
