# Marty Microservices Framework - Ruff Configuration
[tool.ruff]
line-length = 88
target-version = "py310"
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "microservice_project_template/.venv",
    "build",
    "dist",
]

# Enable specific rule sets
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "B",    # flake8-bugbear
    "I",    # isort
    "UP",   # pyupgrade
    "N",    # pep8-naming
    "PT",   # flake8-pytest-style
    "RUF",  # ruff-specific rules
]

ignore = [
    "E501",  # line too long (handled by black)
]

[tool.ruff.isort]
known-first-party = ["scripts"]
combine-as-imports = true

[tool.ruff.per-file-ignores]
"scripts/*" = ["T201"]  # Allow print statements in scripts
"microservice_project_template/**" = ["ALL"]  # Ignore project template
