[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "marty-msf"
version = "1.0.0"
description = "Marty Microservices Framework - Enterprise-grade microservices platform"
authors = [
    {name = "Marty Framework Team", email = "team@marty-msf.com"}
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
keywords = ["microservices", "framework", "fastapi", "docker", "kubernetes"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: System :: Distributed Computing",
]

# Core dependencies
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.5.0",
    "python-multipart>=0.0.6",
    "click>=8.1.0",
    "rich>=13.0.0",
    "jinja2>=3.1.0",
    "toml>=0.10.2",
    "pyyaml>=6.0.0",
    "cookiecutter>=2.5.0",
    "gitpython>=3.1.40",
    "aiokafka>=0.12.0",
    "kafka-python>=2.2.15",
    "prometheus-client>=0.23.1",
    "aiohttp>=3.13.0",
    "aiofiles>=24.1.0",
    "locust>=2.34.0",
    "grpcio>=1.75.1",
    "grpcio-tools>=1.75.1",
]

# Optional dependency groups
[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-json-report>=1.5.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.7.0",
    "pre-commit>=3.5.0",
]

microservices = [
    "aioredis>=2.0.1",
    "asyncpg>=0.29.0",
    "celery>=5.3.0",
    "prometheus-client>=0.19.0",
    "structlog>=23.2.0",
    "tenacity>=8.2.0",
    "httpx>=0.25.0",
]

cloud = [
    "kubernetes>=28.1.0",
    "boto3>=1.34.0",
    "azure-identity>=1.15.0",
    "google-cloud-core>=2.4.0",
]

all = [
    "marty-msf[dev,microservices,cloud]"
]

[project.urls]
Homepage = "https://github.com/marty-framework/marty-microservices-framework"
Documentation = "https://marty-msf.readthedocs.io"
Repository = "https://github.com/marty-framework/marty-microservices-framework"
Issues = "https://github.com/marty-framework/marty-microservices-framework/issues"

[project.scripts]
marty = "marty_cli:cli"
marty-msf = "marty_cli:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["marty_cli*"]

[tool.setuptools.package-data]
marty_cli = ["templates/**/*"]
"*" = ["templates/**/*"]

[dependency-groups]
dev = [
    "build>=1.3.0",
    "pre-commit>=4.3.0",
    "twine>=6.2.0",
]
