apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-template
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: microservice-template
          image: microservice-template:latest
          imagePullPolicy: Never
