apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-template
  labels:
    app.kubernetes.io/name: microservice-template
    app.kubernetes.io/component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice-template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice-template
        app.kubernetes.io/component: api
        version: v1  # For service mesh traffic splitting
      annotations:
        # Prometheus scraping
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
        # Istio sidecar injection (optional, namespace-level injection is preferred)
        sidecar.istio.io/inject: "true"
        # Linkerd injection (optional, namespace-level injection is preferred)
        linkerd.io/inject: enabled
        # Service mesh configuration
        config.linkerd.io/skip-inbound-ports: "9000"  # Skip metrics port
        traffic.sidecar.istio.io/includeInboundPorts: "50051,8080"  # Include only app ports
    spec:
      containers:
        - name: microservice-template
          image: microservice-template:latest
          imagePullPolicy: Never
          ports:
            - name: grpc
              containerPort: 50051
            - name: metrics
              containerPort: 9000
            - name: health
              containerPort: 8080
          env:
            - name: APP_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: microservice-template-config
                  key: environment
            - name: APP_GRPC_PORT
              value: "50051"
            - name: APP_METRICS_PORT
              value: "9000"
            - name: APP_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: microservice-template-config
                  key: otlp_endpoint
          readinessProbe:
            httpGet:
              path: /health/ready
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: health
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      serviceAccountName: microservice-template
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-template
  labels:
    app.kubernetes.io/name: microservice-template
