apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petstore-domain

# Include base configurations
resources:
  - ../../
  - namespace.yaml
  - ../service-mesh/linkerd-policies.yaml
  - ../service-mesh/monitoring.yaml

# Service mesh specific labels
commonLabels:
  app.kubernetes.io/name: petstore-domain
  app.kubernetes.io/component: microservice
  app.kubernetes.io/part-of: petstore-platform
  service-mesh: "linkerd"
  marty.io/service-mesh: "linkerd"

# Linkerd-specific annotations
commonAnnotations:
  # Enable Linkerd sidecar injection
  linkerd.io/inject: enabled
  # Configure Linkerd proxy resources
  config.linkerd.io/proxy-cpu-limit: "100m"
  config.linkerd.io/proxy-memory-limit: "128Mi"
  config.linkerd.io/proxy-cpu-request: "10m"
  config.linkerd.io/proxy-memory-request: "64Mi"
  # Traffic exclusions
  config.linkerd.io/skip-outbound-ports: "443,53"
  config.linkerd.io/skip-inbound-ports: "9000"
  # Service mesh annotations
  marty.io/service-mesh: "linkerd"
  marty.io/circuit-breaker: "enabled"
  marty.io/retry-policy: "enabled"
  marty.io/observability: "enhanced"

# Patches for service mesh integration
patchesStrategicMerge:
  - deployment-patch.yaml

# Configuration for service mesh
configMapGenerator:
  - name: petstore-service-mesh-config
    literals:
      - SERVICE_MESH=linkerd
      - CIRCUIT_BREAKER_ENABLED=true
      - RETRY_POLICY_ENABLED=true
      - FAULT_INJECTION_ENABLED=false
      - RATE_LIMITING_ENABLED=false
      - OBSERVABILITY_ENHANCED=true
      - METRICS_PORT=9000
      - HEALTH_PORT=8080
      - TRACING_ENABLED=true
      - MTLS_MODE=PERMISSIVE
