global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mmf-order-service'
    static_configs:
      - targets: ['order-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mmf-payment-service'
    static_configs:
      - targets: ['payment-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mmf-inventory-service'
    static_configs:
      - targets: ['inventory-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 5s
