apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: order-service-http-server
  namespace: store-system
spec:
  podSelector:
    matchLabels:
      app: order-service
  port: 8001
  proxyProtocol: "HTTP/2"
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: order-service-grpc-server
  namespace: store-system
spec:
  podSelector:
    matchLabels:
      app: order-service
  port: 50051
  proxyProtocol: "gRPC"
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: order-service-http-authz
  namespace: store-system
spec:
  server:
    name: order-service-http-server
  requiredRoutes:
  - pathRegex: "/order-service/.*"
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
  - pathRegex: "/health/.*"
    methods: ["GET"]
  - pathRegex: "/metrics"
    methods: ["GET"]
  client:
    meshTLS:
      serviceAccounts:
      - name: api-gateway
      - name: default
    # Allow health checks and metrics without authentication
    unauthenticated: true
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: order-service-grpc-authz
  namespace: store-system
spec:
  server:
    name: order-service-grpc-server
  requiredRoutes:
  - pathRegex: "/order.service\\..*"
    methods: ["*"]
  client:
    meshTLS:
      serviceAccounts:
      - name: api-gateway
      - name: default
---
apiVersion: policy.linkerd.io/v1alpha1
kind: HTTPRoute
metadata:
  name: order-service-routes
  namespace: store-system
spec:
  parentRefs:
  - name: order-service-http-server
    kind: Server
    group: policy.linkerd.io
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/order-service/"
    backendRefs:
    - name: order-service
      port: 8001
      weight: 100
    timeouts:
      request: 30s
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: "X-Service-Mesh"
          value: "linkerd"
        - name: "X-Service-Name"
          value: "order-service"
  - matches:
    - path:
        type: PathPrefix
        value: "/health/"
    backendRefs:
    - name: order-service
      port: 8001
      weight: 100
    timeouts:
      request: 5s
  - matches:
    - path:
        type: Exact
        value: "/metrics"
    backendRefs:
    - name: order-service
      port: 8001
      weight: 100
    timeouts:
      request: 10s
