apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-domain
  labels:
    app: petstore-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore-domain
  template:
    metadata:
      labels:
        app: petstore-domain
    spec:
      containers:
      - name: petstore-domain
        image: petstore-domain:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: KAFKA_BROKERS
          value: "kafka.observability.svc.cluster.local:9092"
        - name: CONFIG_FILE
          value: "/app/config/enhanced_config.yaml"
        - name: REDIS_URL
          value: "redis://redis.observability.svc.cluster.local:6379"
        - name: JAEGER_ENDPOINT
          value: "http://jaeger.observability.svc.cluster.local:14268/api/traces"
        - name: PROMETHEUS_ENDPOINT
          value: "http://prometheus.observability.svc.cluster.local:9090"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
