apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservice-template-dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patch-deployment.yaml
configMapGenerator:
  - name: microservice-template-config
    behavior: merge
    literals:
      - environment=dev
      - otlp_endpoint=http://otel-collector.monitoring:4317
