# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import greeter_pb2 as greeter__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in greeter_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GreeterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
            "/microservice.template.v1.GreeterService/SayHello",
            request_serializer=greeter__pb2.HelloRequest.SerializeToString,
            response_deserializer=greeter__pb2.HelloResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/microservice.template.v1.GreeterService/HealthCheck",
            request_serializer=greeter__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=greeter__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.GenerateSampleData = channel.unary_unary(
            "/microservice.template.v1.GreeterService/GenerateSampleData",
            request_serializer=greeter__pb2.SampleDataRequest.SerializeToString,
            response_deserializer=greeter__pb2.SampleDataResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeCorrelation = channel.unary_unary(
            "/microservice.template.v1.GreeterService/AnalyzeCorrelation",
            request_serializer=greeter__pb2.CorrelationRequest.SerializeToString,
            response_deserializer=greeter__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeClustering = channel.unary_unary(
            "/microservice.template.v1.GreeterService/AnalyzeClustering",
            request_serializer=greeter__pb2.ClusteringRequest.SerializeToString,
            response_deserializer=greeter__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeDistribution = channel.unary_unary(
            "/microservice.template.v1.GreeterService/AnalyzeDistribution",
            request_serializer=greeter__pb2.DistributionRequest.SerializeToString,
            response_deserializer=greeter__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )


class GreeterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateSampleData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeCorrelation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeClustering(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeDistribution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GreeterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SayHello": grpc.unary_unary_rpc_method_handler(
            servicer.SayHello,
            request_deserializer=greeter__pb2.HelloRequest.FromString,
            response_serializer=greeter__pb2.HelloResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=greeter__pb2.HealthCheckRequest.FromString,
            response_serializer=greeter__pb2.HealthCheckResponse.SerializeToString,
        ),
        "GenerateSampleData": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateSampleData,
            request_deserializer=greeter__pb2.SampleDataRequest.FromString,
            response_serializer=greeter__pb2.SampleDataResponse.SerializeToString,
        ),
        "AnalyzeCorrelation": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeCorrelation,
            request_deserializer=greeter__pb2.CorrelationRequest.FromString,
            response_serializer=greeter__pb2.AnalysisResponse.SerializeToString,
        ),
        "AnalyzeClustering": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeClustering,
            request_deserializer=greeter__pb2.ClusteringRequest.FromString,
            response_serializer=greeter__pb2.AnalysisResponse.SerializeToString,
        ),
        "AnalyzeDistribution": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeDistribution,
            request_deserializer=greeter__pb2.DistributionRequest.FromString,
            response_serializer=greeter__pb2.AnalysisResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "microservice.template.v1.GreeterService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "microservice.template.v1.GreeterService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class GreeterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/microservice.template.v1.GreeterService/SayHello",
            greeter__pb2.HelloRequest.SerializeToString,
            greeter__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/microservice.template.v1.GreeterService/HealthCheck",
            greeter__pb2.HealthCheckRequest.SerializeToString,
            greeter__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateSampleData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/microservice.template.v1.GreeterService/GenerateSampleData",
            greeter__pb2.SampleDataRequest.SerializeToString,
            greeter__pb2.SampleDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeCorrelation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/microservice.template.v1.GreeterService/AnalyzeCorrelation",
            greeter__pb2.CorrelationRequest.SerializeToString,
            greeter__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeClustering(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/microservice.template.v1.GreeterService/AnalyzeClustering",
            greeter__pb2.ClusteringRequest.SerializeToString,
            greeter__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeDistribution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/microservice.template.v1.GreeterService/AnalyzeDistribution",
            greeter__pb2.DistributionRequest.SerializeToString,
            greeter__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
