apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    linkerd.io/control-plane-ns: linkerd
    config.linkerd.io/admission-webhooks: disabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    linkerd.io/inject: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-viz
  labels:
    linkerd.io/extension: viz
    config.linkerd.io/admission-webhooks: disabled
  annotations:
    linkerd.io/inject: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-jaeger
  labels:
    linkerd.io/extension: jaeger
    config.linkerd.io/admission-webhooks: disabled
  annotations:
    linkerd.io/inject: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-multicluster
  labels:
    linkerd.io/extension: multicluster
    config.linkerd.io/admission-webhooks: disabled
  annotations:
    linkerd.io/inject: disabled
---
# Framework namespace with Linkerd injection
apiVersion: v1
kind: Namespace
metadata:
  name: microservice-framework
  labels:
    linkerd.io/inject: enabled
    config.linkerd.io/admission-webhooks: enabled
    name: microservice-framework
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/skip-inbound-ports: "9092,9093"  # Skip Kafka ports
    config.linkerd.io/skip-outbound-ports: "443,53"     # Skip HTTPS and DNS
