apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: order-service-dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patch-deployment.yaml
configMapGenerator:
  - name: order-service-config
    behavior: merge
    literals:
      - environment=dev
      - otlp_endpoint=http://otel-collector.monitoring:4317
