# Base configuration for microservices framework
# This file contains common configuration patterns shared across all environments

# Default ports for common services
default_ports: &default_ports
  user_service: 8001
  order_service: 8002
  payment_service: 8003
  notification_service: 8004
  api_gateway: 8000

# Common database configuration patterns
common_database: &common_database
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  ssl_mode: prefer
  connection_timeout: 30

# Common security configuration (ENFORCED BY DEFAULT)
common_security: &common_security
  grpc_tls:
    enabled: true
    mtls: true
    require_client_auth: true
    verify_hostname: true
    server_cert: "/etc/tls/server/tls.crt"
    server_key: "/etc/tls/server/tls.key"
    client_ca: "/etc/tls/ca/ca.crt"
    client_cert: "/etc/tls/client/tls.crt"
    client_key: "/etc/tls/client/tls.key"

  auth:
    required: true
    jwt:
      enabled: true
      algorithm: "HS256"
      secret: ""  # Must be set via environment variable
    api_key_enabled: true
    client_cert:
      enabled: true
      extract_subject: true

  authz:
    enabled: true
    policy_config: "/etc/config/policy.yaml"
    default_action: "deny"

# Common logging configuration
common_logging: &common_logging
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - console
    - file
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Common monitoring configuration
common_monitoring: &common_monitoring
  enabled: true
  metrics_port: 9090
  health_check_port: 8080
  prometheus_enabled: true
  tracing_enabled: true

# Common resilience patterns
common_resilience: &common_resilience
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60
    half_open_max_calls: 3

  retry_policy:
    max_attempts: 3
    backoff_multiplier: 1.5
    max_delay_seconds: 30

  # Timeout configurations for different dependency types
  timeouts:
    default_timeout: 30.0
    database_timeout: 10.0
    api_call_timeout: 15.0
    message_queue_timeout: 5.0
    cache_timeout: 2.0
    file_operation_timeout: 30.0
    circuit_breaker_timeout: 60.0

  # Bulkhead configurations for resource isolation
  bulkheads:
    # Database operations
    database:
      max_concurrent: 10
      timeout_seconds: 15.0
      bulkhead_type: "semaphore"
      reject_on_full: false
      enable_circuit_breaker: true

    # External API calls
    external_api:
      max_concurrent: 15
      timeout_seconds: 20.0
      bulkhead_type: "semaphore"
      reject_on_full: true
      enable_circuit_breaker: true
      circuit_breaker_failure_threshold: 3

    # Cache operations
    cache:
      max_concurrent: 50
      timeout_seconds: 2.0
      bulkhead_type: "semaphore"
      reject_on_full: true
      enable_circuit_breaker: false

    # Message queue operations
    message_queue:
      max_concurrent: 20
      timeout_seconds: 10.0
      bulkhead_type: "semaphore"
      reject_on_full: false
      enable_circuit_breaker: true
      circuit_breaker_failure_threshold: 5

    # File system operations
    file_system:
      max_concurrent: 8
      timeout_seconds: 30.0
      bulkhead_type: "thread_pool"
      reject_on_full: true
      enable_circuit_breaker: false

    # CPU-intensive operations
    cpu_intensive:
      max_concurrent: 4
      timeout_seconds: 60.0
      bulkhead_type: "thread_pool"
      reject_on_full: true
      enable_circuit_breaker: false

# Service ports
ports: *default_ports

# Default configurations
security: *common_security
logging: *common_logging
monitoring: *common_monitoring
resilience: *common_resilience

# Database configurations per service (enforcing database per service pattern)
database:
  user_service:
    <<: *common_database
    host: "${DB_HOST:-localhost}"
    port: "${DB_PORT:-5432}"
    database: "user_service_db"
    username: "${USER_DB_USERNAME:-user_svc}"
    password: "${USER_DB_PASSWORD:-}"

  order_service:
    <<: *common_database
    host: "${DB_HOST:-localhost}"
    port: "${DB_PORT:-5432}"
    database: "order_service_db"
    username: "${ORDER_DB_USERNAME:-order_svc}"
    password: "${ORDER_DB_PASSWORD:-}"

  payment_service:
    <<: *common_database
    host: "${DB_HOST:-localhost}"
    port: "${DB_PORT:-5432}"
    database: "payment_service_db"
    username: "${PAYMENT_DB_USERNAME:-payment_svc}"
    password: "${PAYMENT_DB_PASSWORD:-}"

  notification_service:
    <<: *common_database
    host: "${DB_HOST:-localhost}"
    port: "${DB_PORT:-5432}"
    database: "notification_service_db"
    username: "${NOTIFICATION_DB_USERNAME:-notification_svc}"
    password: "${NOTIFICATION_DB_PASSWORD:-}"

# Common service configuration patterns
services:
  user_service:
    max_connections: 100
    request_timeout: 30
    jwt_expiry_hours: 24
    password_hash_rounds: 12
    enable_email_verification: true

  order_service:
    max_concurrent_orders: 50
    order_timeout_minutes: 15
    inventory_check_enabled: true
    payment_timeout_seconds: 300

  payment_service:
    max_transaction_amount: 10000
    fraud_check_enabled: true
    pci_compliance_mode: true
    encryption_key_rotation_days: 30

  notification_service:
    max_queue_size: 1000
    retry_attempts: 3
    batch_size: 100
    rate_limit_per_minute: 60

# Plugin system configuration
plugins:
  enabled: true
  auto_discovery: true
  discovery_paths:
    - "./plugins"
    - "/opt/mmf/plugins"
  config_dir: "./config/plugins"

  # Isolation level for plugin execution
  isolation_level: "process"  # Options: process, thread, none

  # Plugin loading configuration
  loading:
    parallel: true
    timeout_seconds: 30
    retry_attempts: 3

  # Default plugins to load (can be overridden per environment)
  default_plugins:
    - name: "production_payment"
      enabled: true
      priority: 100

  # Plugin security settings
  security:
    require_signature: false  # Set to true in production
    allowed_sources:
      - "local"
      - "official"
    sandboxing:
      enabled: false  # Enable in production
      resource_limits:
        memory_mb: 512
        cpu_percent: 50
