# Development environment configuration
# Inherits from base configuration with development-specific overrides
# Compatible with unified configuration management system

# Service metadata overrides for development
service:
  environment: "development"
  debug: true
  log_level: "DEBUG"

# Unified configuration overrides for development
unified_config:
  enable_secrets: true
  secret_backends: ["environment", "file"]
  enable_hot_reload: true

# Development security settings (less strict)
security:
  grpc_tls:
    enabled: false
  auth:
    required: false
    jwt:
      secret: "${SECRET:jwt_secret}"
  authz:
    enabled: false

# Development monitoring
monitoring:
  enabled: true
  tracing_enabled: false
  service_type: "grpc"

# gRPC configuration for development
grpc:
  port: 50051
  max_workers: 5
  reflection_enabled: true

# Development database
database:
  host: "localhost"
  port: 5432
  username: "dev_user"
  password: "dev_password"
  ssl_mode: "disable"

# Development secrets
secrets:
  database_host: "localhost"
  database_username: "dev_user"
  database_password: "dev_password"
  jwt_secret: "dev_jwt_secret_not_secure"
  service_api_key: "dev_api_key_12345"
  jaeger_endpoint: ""
