apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marty-dev

resources:
  - namespace.yaml
  - ../marty-services

patches:
  - path: patch-dev-deployment.yaml
    target:
      kind: Deployment
      name: order-service
  - path: patch-dev-hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: order-service

configMapGenerator:
  - name: order-service-config
    behavior: merge
    literals:
      - environment=development
      - log_level=DEBUG
      - database_migration_enabled=true
      - kafka_brokers=kafka.marty-dev:9092
      - otlp_endpoint=http://otel-collector.monitoring:4317

secretGenerator:
  - name: order-service-secrets
    literals:
      - database_url=postgresql://dev_user:dev_pass@postgres.marty-dev:5432/marty_dev
      - redis_url=redis://redis.marty-dev:6379/0

# Use development images
images:
  - name: order-service
    newTag: dev-latest

# Add development-specific labels
commonLabels:
  environment: development
  tier: dev

# Add development annotations
commonAnnotations:
  marty.io/environment: development
  marty.io/auto-deploy: enabled
