apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discovery-config
  namespace: marty-framework
  labels:
    app: service-discovery
    component: infrastructure
    version: v1
    part-of: marty-framework
data:
  # Service Configuration
  service_name: "service-discovery"
  environment: "kubernetes"
  log_level: "INFO"
  log_format: "json"

  # Registry Configuration
  registry_type: "kubernetes"

  # Consul Configuration (if using Consul)
  consul_host: "consul.marty-framework.svc.cluster.local"
  consul_port: "8500"
  consul_scheme: "http"
  consul_datacenter: "dc1"
  consul_verify_ssl: "true"
  consul_timeout: "30"
  consul_session_ttl: "60"
  consul_check_interval: "30s"
  consul_check_timeout: "10s"
  consul_deregister_critical_after: "1m"

  # etcd Configuration (if using etcd)
  etcd_host: "etcd.marty-framework.svc.cluster.local"
  etcd_port: "2379"
  etcd_timeout: "30"
  etcd_lease_ttl: "60"
  etcd_key_prefix: "/services/"
  etcd_enable_watch: "true"

  # Kubernetes Configuration
  k8s_namespace: "marty-framework"
  k8s_in_cluster: "true"
  k8s_watch_endpoints: "true"
  k8s_watch_services: "true"
  k8s_enable_annotations: "true"
  k8s_service_port_name: "http"
  k8s_discovery_annotation: "marty-framework/discovery"
  k8s_metadata_annotation_prefix: "marty-framework/"

  # Health Check Configuration
  health_check_enabled: "true"
  health_check_strategy: "http"
  health_check_interval: "30"
  health_check_timeout: "10"
  health_check_retries: "3"
  health_check_failure_threshold: "3"
  health_check_success_threshold: "1"
  health_check_http_path: "/health"
  health_check_http_method: "GET"
  health_check_http_expected_status: "200"

  # Load Balancing Configuration
  load_balancing_strategy: "round_robin"
  load_balancing_health_check_enabled: "true"
  load_balancing_sticky_sessions: "false"
  load_balancing_session_affinity_key: "client_ip"
  load_balancing_circuit_breaker_enabled: "true"
  load_balancing_failure_threshold: "5"
  load_balancing_recovery_timeout: "30"

  # Service Registration Configuration
  registration_auto_register: "true"
  registration_register_on_startup: "true"
  registration_deregister_on_shutdown: "true"
  registration_heartbeat_interval: "30"
  registration_heartbeat_timeout: "10"
  registration_retry_attempts: "3"
  registration_retry_delay: "2.0"
  registration_retry_backoff_factor: "2.0"

  # Discovery Configuration
  discovery_enabled: "true"
  discovery_cache_enabled: "true"
  discovery_cache_ttl: "300"
  discovery_cache_size: "1000"
  discovery_refresh_interval: "60"
  discovery_background_refresh: "true"
  discovery_prefer_local_instances: "false"
  discovery_exclude_unhealthy: "true"
  discovery_strategies: "registry,dns"
  discovery_dns_domain: "cluster.local"

  # Monitoring Configuration
  metrics_enabled: "true"
  metrics_port: "9090"
  metrics_path: "/metrics"
  tracing_enabled: "false"
  jaeger_endpoint: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"
  trace_sample_rate: "0.1"
  log_discovery_events: "true"
  log_health_checks: "false"
  alerting_enabled: "false"
  alert_webhook_url: ""

  # Security Configuration
  authentication_enabled: "false"
  authorization_enabled: "false"
  tls_enabled: "false"
  tls_verify: "true"
  api_key_enabled: "false"
  api_key_header: "X-API-Key"
  jwt_enabled: "false"
  jwt_algorithm: "HS256"
  jwt_expiration: "3600"

  # Clustering Configuration
  cluster_enabled: "true"
  failover_enabled: "true"

  # Application Configuration
  app_config.yaml: |
    service:
      name: service-discovery
      host: 0.0.0.0
      port: 8090
      environment: kubernetes

    registry:
      type: kubernetes
      kubernetes:
        namespace: marty-framework
        in_cluster: true
        watch_endpoints: true
        watch_services: true
        enable_annotations: true
        service_port_name: http
        discovery_annotation: marty-framework/discovery
        metadata_annotation_prefix: marty-framework/

    health_check:
      enabled: true
      strategy: http
      interval: 30
      timeout: 10
      retries: 3
      failure_threshold: 3
      success_threshold: 1
      http_path: /health
      http_method: GET
      http_expected_status: 200

    load_balancing:
      strategy: round_robin
      health_check_enabled: true
      sticky_sessions: false
      session_affinity_key: client_ip
      circuit_breaker_enabled: true
      failure_threshold: 5
      recovery_timeout: 30

    registration:
      auto_register: true
      register_on_startup: true
      deregister_on_shutdown: true
      heartbeat_interval: 30
      heartbeat_timeout: 10
      retry_attempts: 3
      retry_delay: 2.0
      retry_backoff_factor: 2.0

    discovery:
      enabled: true
      cache_enabled: true
      cache_ttl: 300
      cache_size: 1000
      refresh_interval: 60
      background_refresh: true
      prefer_local_instances: false
      exclude_unhealthy: true
      strategies:
        - registry
        - dns
      dns_domain: cluster.local

    monitoring:
      metrics_enabled: true
      metrics_port: 9090
      metrics_path: /metrics
      tracing_enabled: false
      jaeger_endpoint: http://jaeger-collector.observability.svc.cluster.local:14268/api/traces
      trace_sample_rate: 0.1
      log_level: INFO
      log_format: json
      log_discovery_events: true
      log_health_checks: false
      alerting_enabled: false

    security:
      authentication_enabled: false
      authorization_enabled: false
      tls_enabled: false
      tls_verify: true
      api_key_enabled: false
      api_key_header: X-API-Key
      jwt_enabled: false
      jwt_algorithm: HS256
      jwt_expiration: 3600

    cluster:
      enabled: true
      failover_enabled: true
