apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: marty-framework
  labels:
    app: service-discovery
    component: infrastructure
    version: v1
    part-of: marty-framework
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8090"
    prometheus.io/path: "/metrics"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 8090
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: service-discovery

---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-headless
  namespace: marty-framework
  labels:
    app: service-discovery
    component: infrastructure
    version: v1
    part-of: marty-framework
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http
    port: 8090
    targetPort: http
    protocol: TCP
  selector:
    app: service-discovery

---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-external
  namespace: marty-framework
  labels:
    app: service-discovery
    component: infrastructure
    version: v1
    part-of: marty-framework
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "service-discovery.marty-framework.io"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8     # Internal network access only
  - 172.16.0.0/12  # Private network ranges
  - 192.168.0.0/16 # Private network ranges
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  selector:
    app: service-discovery
