"""Messaging system for reliable message passing and event handling."""

# Import from API layer (contracts and interfaces)
from .api import (
    BackendConfig,
    BackendType,
    ConsumerConfig,
    DLQConfig,
    DLQMessage,
    DLQPolicy,
    IDLQManager,
    IMessageBackend,
    IMessageConsumer,
    IMessageExchange,
    IMessageMiddleware,
    IMessageProducer,
    IMessageQueue,
    IMessageRouter,
    IMessageSerializer,
    IMessagingManager,
    MatchType,
    Message,
    MessageHeaders,
    MessagePattern,
    MessagePriority,
    MessageStatus,
    MessagingConfig,
    MessagingConnectionError,
    MessagingError,
    MiddlewareStage,
    MiddlewareType,
    ProducerConfig,
    RetryConfig,
    RetryStrategy,
    RoutingConfig,
    RoutingRule,
    RoutingType,
)

# Import from bootstrap layer (concrete implementations)
from .bootstrap import (
    DLQHandler,
    DLQManager,
    EventStreamManager,
    JSONMessageSerializer,
    MemoryMessageBackend,
    MessageBus,
    MessageConsumer,
    MessageProducer,
    MessageQueue,
    MessageRouter,
    MessagingManager,
    MiddlewareChain,
    create_messaging_manager,
    setup_messaging_system,
)

__all__ = [
    # API Layer - Interfaces and Contracts
    "BackendConfig",
    "BackendType",
    "ConsumerConfig",
    "DLQConfig",
    "IDLQManager",
    "IMessageBackend",
    "IMessageConsumer",
    "IMessageExchange",
    "IMessageMiddleware",
    "IMessageProducer",
    "IMessageQueue",
    "IMessageRouter",
    "IMessageSerializer",
    "IMessagingManager",
    "Message",
    "MessageHeaders",
    "MessagePattern",
    "MessagePriority",
    "MessageStatus",
    "MessagingConfig",
    "MessagingConnectionError",
    "MessagingError",
    "MiddlewareStage",
    "MiddlewareType",
    "ProducerConfig",
    "RoutingConfig",
    "RoutingRule",
    "RoutingType",
    "MatchType",
    "RetryConfig",
    "RetryStrategy",    # Bootstrap Layer - Concrete Implementations
    "DLQHandler",
    "DLQManager",
    "JSONMessageSerializer",
    "MemoryMessageBackend",
    "MessageConsumer",
    "MessageProducer",
    "MessageRouter",
    "MessagingManager",
    "MiddlewareChain",
    "create_messaging_manager",
    "setup_messaging_system",
    "MessageQueue",
    "EventStreamManager",
    "MessageBus",
]
