apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-domain
spec:
  template:
    metadata:
      annotations:
        # Enhanced Istio sidecar configuration
        sidecar.istio.io/proxyCPU: "50m"
        sidecar.istio.io/proxyMemory: "256Mi"
        sidecar.istio.io/proxyMemoryLimit: "512Mi"
        sidecar.istio.io/logLevel: "info"
        # Traffic management
        traffic.sidecar.istio.io/excludeOutboundPorts: "443,53"
        traffic.sidecar.istio.io/includeInboundPorts: "8080,9000"
        # Service mesh metadata
        marty.io/service-mesh: istio
        marty.io/version: v1
        marty.io/circuit-breaker: enabled
        marty.io/retry-policy: enabled
        # Observability
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: petstore-domain
        env:
        - name: SERVICE_MESH
          value: "istio"
        - name: CIRCUIT_BREAKER_ENABLED
          value: "true"
        - name: RETRY_POLICY_ENABLED
          value: "true"
        - name: MTLS_ENABLED
          value: "true"
        - name: TRACING_ENABLED
          value: "true"
        - name: JAEGER_ENDPOINT
          value: "http://jaeger.istio-system.svc.cluster.local:14268/api/traces"
        - name: PROMETHEUS_ENDPOINT
          value: "http://prometheus.istio-system.svc.cluster.local:9090"
        - name: SERVICE_MESH_METRICS_PORT
          value: "15020"
        ports:
        - name: metrics
          containerPort: 9000
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
