apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petstore-domain

# Include base configurations
resources:
  - ../../
  - namespace.yaml
  - ../service-mesh/istio-policies.yaml

# Service mesh specific labels
commonLabels:
  app.kubernetes.io/name: petstore-domain
  app.kubernetes.io/component: microservice
  app.kubernetes.io/part-of: petstore-platform
  service-mesh: "istio"
  marty.io/service-mesh: "istio"

# Istio-specific annotations
commonAnnotations:
  # Enable Istio sidecar injection
  sidecar.istio.io/inject: "true"
  # Configure Istio proxy resources
  sidecar.istio.io/proxyCPU: "10m"
  sidecar.istio.io/proxyMemory: "128Mi"
  sidecar.istio.io/logLevel: "info"
  # Traffic exclusions
  traffic.sidecar.istio.io/excludeOutboundPorts: "443,53"
  traffic.sidecar.istio.io/includeInboundPorts: "8080"
  # Service mesh annotations
  marty.io/service-mesh: "istio"
  marty.io/circuit-breaker: "enabled"
  marty.io/retry-policy: "enabled"
  marty.io/observability: "enhanced"

# Patches for service mesh integration
patchesStrategicMerge:
  - deployment-patch.yaml

# Configuration for service mesh
configMapGenerator:
  - name: petstore-service-mesh-config
    literals:
      - SERVICE_MESH=istio
      - CIRCUIT_BREAKER_ENABLED=true
      - RETRY_POLICY_ENABLED=true
      - FAULT_INJECTION_ENABLED=false
      - RATE_LIMITING_ENABLED=true
      - OBSERVABILITY_ENHANCED=true
      - METRICS_PORT=9000
      - HEALTH_PORT=8080
      - TRACING_ENABLED=true
      - MTLS_MODE=STRICT
