name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - name: Install Python
        run: uv python install 3.11
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Ruff lint
        run: uv run ruff check src tests
      - name: Type checking
        run: uv run mypy src/microservice_template
      - name: Unit + integration + e2e tests
        run: uv run pytest -m "not build"
      - name: Build test
        run: uv run pip wheel . --no-deps --wheel-dir build
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: .pytest_cache
          if-no-files-found: ignore
