apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    # Service mesh annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For cloud deployments
    # Istio traffic policy
    traffic.istio.io/nodePortLB: disable
    # Linkerd traffic policy
    config.linkerd.io/disable: "false"
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
    protocol: TCP
  - name: http
    port: 8080
    targetPort: health
    protocol: TCP
  - name: metrics
    port: 9000
    targetPort: metrics
    protocol: TCP
