apiVersion: v1
kind: Namespace
metadata:
  name: marty-dev
  labels:
    name: marty-dev
    app.kubernetes.io/part-of: marty-platform
    environment: development
    istio-injection: enabled  # Enable Istio injection
    linkerd.io/inject: enabled  # Enable Linkerd injection
  annotations:
    marty.io/environment: development
    marty.io/managed-by: kustomize
