apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace | default "microservices" }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: microservice
    marty.framework/phase: "phase2"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - name: grpc
    port: {{ .Values.service.grpcPort | default 50051 }}
    targetPort: grpc
    protocol: TCP
  - name: http
    port: {{ .Values.service.httpPort | default 8080 }}
    targetPort: http
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.metricsPort | default 9090 }}
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
  namespace: {{ .Values.namespace | default "microservices" }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: headless
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: {{ .Values.service.grpcPort | default 50051 }}
    targetPort: grpc
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- if .Values.service.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-lb
  namespace: {{ .Values.namespace | default "microservices" }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: loadbalancer
  annotations:
    {{- if eq .Values.cloud.provider "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-type: {{ .Values.service.loadBalancer.awsType | default "nlb" }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    {{- end }}
    {{- if eq .Values.cloud.provider "gcp" }}
    cloud.google.com/load-balancer-type: {{ .Values.service.loadBalancer.gcpType | default "Internal" }}
    {{- end }}
    {{- if eq .Values.cloud.provider "azure" }}
    service.beta.kubernetes.io/azure-load-balancer-internal: {{ .Values.service.loadBalancer.azureInternal | default "true" | quote }}
    {{- end }}
spec:
  type: LoadBalancer
  {{- if .Values.service.loadBalancer.sourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancer.sourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end }}
  ports:
  - name: grpc
    port: {{ .Values.service.grpcPort | default 50051 }}
    targetPort: grpc
    protocol: TCP
  - name: http
    port: {{ .Values.service.httpPort | default 8080 }}
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
