route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    continue: true
  - match:
      team: business
    receiver: 'business-team'
  - match:
      team: platform
    receiver: 'platform-team'

receivers:
- name: 'default'
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#alerts'
    title: 'Marty Microservices Alert'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Service:* {{ .Labels.service_name }}
      {{ end }}

- name: 'critical-alerts'
  slack_configs:
  - api_url: 'YOUR_CRITICAL_SLACK_WEBHOOK_URL'
    channel: '#critical-alerts'
    title: '🚨 CRITICAL ALERT 🚨'
    text: |
      {{ range .Alerts }}
      *CRITICAL ALERT*
      *Service:* {{ .Labels.service_name }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Runbook:* {{ .Annotations.runbook_url }}
      {{ end }}
  email_configs:
  - to: 'oncall@example.com'
    from: 'alerts@example.com'
    smarthost: 'localhost:587'
    subject: 'CRITICAL: Marty Microservice Alert'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service_name }}
      Severity: {{ .Labels.severity }}
      Runbook: {{ .Annotations.runbook_url }}
      {{ end }}

- name: 'platform-team'
  slack_configs:
  - api_url: 'YOUR_PLATFORM_SLACK_WEBHOOK_URL'
    channel: '#platform-alerts'
    title: 'Platform Alert'
    text: |
      {{ range .Alerts }}
      *Platform Alert*
      *Service:* {{ .Labels.service_name }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      {{ end }}

- name: 'business-team'
  slack_configs:
  - api_url: 'YOUR_BUSINESS_SLACK_WEBHOOK_URL'
    channel: '#business-alerts'
    title: 'Business Metrics Alert'
    text: |
      {{ range .Alerts }}
      *Business Alert*
      *Service:* {{ .Labels.service_name }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@example.com'
