---
# ServiceMonitor for Prometheus to scrape Istio metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petstore-domain-istio-metrics
  namespace: petstore-domain
  labels:
    app.kubernetes.io/managed-by: marty-msf
    marty.io/monitoring-type: service-mesh
    marty.io/service: petstore-domain
    marty.io/mesh: istio
spec:
  selector:
    matchLabels:
      app: petstore-domain
  endpoints:
  # Envoy proxy metrics
  - port: http-monitoring
    path: /stats/prometheus
    interval: 30s
    scrapeTimeout: 10s
  # Application metrics
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
# Telemetry configuration for Istio
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: petstore-domain-telemetry
  namespace: petstore-domain
  labels:
    app.kubernetes.io/managed-by: marty-msf
    marty.io/monitoring-type: service-mesh
    marty.io/service: petstore-domain
    marty.io/mesh: istio
spec:
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: ALL_METRICS
      tagOverrides:
        source_app:
          value: "%{SOURCE_APP | 'unknown'}"
        destination_app:
          value: "%{DESTINATION_APP | 'unknown'}"
        method:
          value: "%{REQUEST_PROTOCOL | 'unknown'}"
  accessLogging:
  - providers:
    - name: otel
  tracing:
  - providers:
    - name: jaeger
---
# Grafana Dashboard ConfigMap for Petstore Domain
apiVersion: v1
kind: ConfigMap
metadata:
  name: petstore-domain-dashboard
  namespace: petstore-domain
  labels:
    app.kubernetes.io/managed-by: marty-msf
    marty.io/monitoring-type: dashboard
    marty.io/service: petstore-domain
    grafana_dashboard: "1"
data:
  petstore-domain-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Petstore Domain Service Mesh Metrics",
        "tags": ["marty-msf", "petstore", "service-mesh"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate(istio_request_total{destination_service_name=\"petstore-domain-service\"}[5m]))",
                "legendFormat": "RPS"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "reqps"
              }
            },
            "gridPos": {"h": 8, "w": 8, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Success Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate(istio_request_total{destination_service_name=\"petstore-domain-service\",response_code!~\"5.*\"}[5m])) / sum(rate(istio_request_total{destination_service_name=\"petstore-domain-service\"}[5m])) * 100",
                "legendFormat": "Success Rate"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent",
                "min": 0,
                "max": 100
              }
            },
            "gridPos": {"h": 8, "w": 8, "x": 8, "y": 0}
          },
          {
            "id": 3,
            "title": "P99 Latency",
            "type": "stat",
            "targets": [
              {
                "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"petstore-domain-service\"}[5m])) by (le))",
                "legendFormat": "P99"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "ms"
              }
            },
            "gridPos": {"h": 8, "w": 8, "x": 16, "y": 0}
          },
          {
            "id": 4,
            "title": "Request Volume Over Time",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(istio_request_total{destination_service_name=\"petstore-domain-service\"}[5m])) by (source_app)",
                "legendFormat": "{{source_app}}"
              }
            ],
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8}
          },
          {
            "id": 5,
            "title": "Circuit Breaker Status",
            "type": "graph",
            "targets": [
              {
                "expr": "envoy_cluster_circuit_breakers_default_cx_open{cluster_name=~\".*petstore-domain.*\"}",
                "legendFormat": "Open Circuits"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 16}
          },
          {
            "id": 6,
            "title": "Retry Metrics",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(envoy_cluster_retry_upstream_rq_retry{cluster_name=~\".*petstore-domain.*\"}[5m]))",
                "legendFormat": "Retries"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 16}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }
---
# Prometheus Rule for Petstore Domain Alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: petstore-domain-service-mesh-alerts
  namespace: petstore-domain
  labels:
    app.kubernetes.io/managed-by: marty-msf
    marty.io/monitoring-type: alerts
    marty.io/service: petstore-domain
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: petstore-domain.service-mesh
    rules:
    - alert: PetstoreDomainHighErrorRate
      expr: |
        (
          sum(rate(istio_request_total{destination_service_name="petstore-domain-service",response_code=~"5.*"}[5m])) /
          sum(rate(istio_request_total{destination_service_name="petstore-domain-service"}[5m]))
        ) * 100 > 5
      for: 2m
      labels:
        severity: warning
        service: petstore-domain
      annotations:
        summary: "High error rate in Petstore Domain service"
        description: "Petstore Domain service has an error rate of {{ $value }}% for more than 2 minutes"

    - alert: PetstoreDomainHighLatency
      expr: |
        histogram_quantile(0.99,
          sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name="petstore-domain-service"}[5m])) by (le)
        ) > 1000
      for: 5m
      labels:
        severity: warning
        service: petstore-domain
      annotations:
        summary: "High latency in Petstore Domain service"
        description: "Petstore Domain service 99th percentile latency is {{ $value }}ms for more than 5 minutes"

    - alert: PetstoreDomainCircuitBreakerOpen
      expr: |
        envoy_cluster_circuit_breakers_default_cx_open{cluster_name=~".*petstore-domain.*"} > 0
      for: 1m
      labels:
        severity: critical
        service: petstore-domain
      annotations:
        summary: "Circuit breaker is open for Petstore Domain"
        description: "Circuit breaker has been open for Petstore Domain service for more than 1 minute"

    - alert: PetstoreDomainLowSuccessRate
      expr: |
        (
          sum(rate(istio_request_total{destination_service_name="petstore-domain-service",response_code!~"5.*"}[5m])) /
          sum(rate(istio_request_total{destination_service_name="petstore-domain-service"}[5m]))
        ) * 100 < 95
      for: 5m
      labels:
        severity: critical
        service: petstore-domain
      annotations:
        summary: "Low success rate in Petstore Domain service"
        description: "Petstore Domain service success rate is {{ $value }}% for more than 5 minutes"
