#!/bin/bash
# Script Commands Summary
# ======================

echo "🚀 Marty Microservices Framework - Script Commands"
echo "================================================="
echo ""
echo "Now available via Makefile (npm-like scripts):"
echo ""

echo "📋 Test Commands:"
echo "  make test                     - Run comprehensive framework tests"
echo "  make test-unit               - Run unit tests only"
echo "  make test-integration        - Run integration tests only"
echo "  make test-e2e                - Run end-to-end tests"
echo "  make test-coverage           - Run tests with coverage report"
echo "  make test-fast               - Run tests with fail-fast mode"
echo ""

echo "🎭 Kind + Playwright E2E Commands:"
echo "  make test-kind-playwright             - Run Kind + Playwright E2E tests"
echo "  make test-kind-playwright-all         - Run all Kind + Playwright tests with options"
echo "  make test-kind-playwright-dashboard   - Run dashboard tests only"
echo "  make test-kind-playwright-visual      - Run visual regression tests"
echo "  make test-kind-playwright-debug       - Run tests with browser visible"
echo ""

echo "🔧 Development Commands:"
echo "  make lint                    - Run ruff linting"
echo "  make lint-fix                - Run ruff linting with auto-fix"
echo "  make format                  - Format code with ruff"
echo "  make typecheck               - Run mypy type checking"
echo "  make security                - Run security checks with bandit"
echo "  make pre-commit-install      - Install pre-commit hooks"
echo "  make pre-commit-run          - Run pre-commit on all files"
echo ""

echo "📦 Setup Commands:"
echo "  make setup-dev               - Setup complete development environment"
echo "  make setup-all               - Setup environment with all extras"
echo "  make install                 - Install framework with UV"
echo "  make clean                   - Clean build artifacts and cache files"
echo ""

echo "📚 Additional Commands:"
echo "  make build                   - Build the package"
echo "  make docs-serve              - Serve documentation locally"
echo "  make demo-e2e                - Run the Kind + Playwright E2E demo"
echo "  make help                    - Show all available commands"
echo ""

echo "💡 Usage Examples:"
echo ""
echo "# Quick development setup:"
echo "make setup-dev"
echo ""
echo "# Run Kind + Playwright E2E tests:"
echo "make test-kind-playwright"
echo ""
echo "# Run tests with coverage:"
echo "make test-coverage"
echo ""
echo "# Format and lint code:"
echo "make format && make lint"
echo ""
echo "# Run E2E tests in debug mode (browser visible):"
echo "make test-kind-playwright-debug"
echo ""

echo "🔗 Alternative Execution Methods:"
echo ""
echo "# Direct UV execution:"
echo "uv run pytest tests/e2e/test_kind_playwright_e2e.py -v -s"
echo ""
echo "# Shell script execution:"
echo "./scripts/run_kind_playwright_e2e.sh"
echo ""
echo "# Simple standalone test:"
echo "python tests/e2e/simple_kind_playwright_test.py"
echo ""

echo "✅ All commands are now available! Use 'make help' for the complete list."
