apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-template
spec:
  replicas: 1  # Single replica for development
  template:
    spec:
      containers:
        - name: microservice-template
          # Development-specific configurations
          env:
            - name: DEBUG
              value: "true"
            - name: HOT_RELOAD
              value: "true"
            - name: CORS_ORIGINS
              value: "*"  # Allow all origins in dev
          # Relaxed resource limits for development
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi
