apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: {{SERVICE_NAME}}-http-server
  namespace: {{NAMESPACE}}
spec:
  podSelector:
    matchLabels:
      app: {{SERVICE_NAME}}
  port: {{HTTP_PORT}}
  proxyProtocol: "HTTP/2"
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: {{SERVICE_NAME}}-grpc-server
  namespace: {{NAMESPACE}}
spec:
  podSelector:
    matchLabels:
      app: {{SERVICE_NAME}}
  port: {{GRPC_PORT}}
  proxyProtocol: "gRPC"
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: {{SERVICE_NAME}}-http-authz
  namespace: {{NAMESPACE}}
spec:
  server:
    name: {{SERVICE_NAME}}-http-server
  requiredRoutes:
  - pathRegex: "/{{SERVICE_NAME}}/.*"
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
  - pathRegex: "/health/.*"
    methods: ["GET"]
  - pathRegex: "/metrics"
    methods: ["GET"]
  client:
    meshTLS:
      serviceAccounts:
      - name: api-gateway
      - name: default
    # Allow health checks and metrics without authentication
    unauthenticated: true
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: {{SERVICE_NAME}}-grpc-authz
  namespace: {{NAMESPACE}}
spec:
  server:
    name: {{SERVICE_NAME}}-grpc-server
  requiredRoutes:
  - pathRegex: "/{{PACKAGE_NAME}}\\..*"
    methods: ["*"]
  client:
    meshTLS:
      serviceAccounts:
      - name: api-gateway
      - name: default
---
apiVersion: policy.linkerd.io/v1alpha1
kind: HTTPRoute
metadata:
  name: {{SERVICE_NAME}}-routes
  namespace: {{NAMESPACE}}
spec:
  parentRefs:
  - name: {{SERVICE_NAME}}-http-server
    kind: Server
    group: policy.linkerd.io
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/{{SERVICE_NAME}}/"
    backendRefs:
    - name: {{SERVICE_NAME}}
      port: {{HTTP_PORT}}
      weight: 100
    timeouts:
      request: 30s
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: "X-Service-Mesh"
          value: "linkerd"
        - name: "X-Service-Name"
          value: "{{SERVICE_NAME}}"
  - matches:
    - path:
        type: PathPrefix
        value: "/health/"
    backendRefs:
    - name: {{SERVICE_NAME}}
      port: {{HTTP_PORT}}
      weight: 100
    timeouts:
      request: 5s
  - matches:
    - path:
        type: Exact
        value: "/metrics"
    backendRefs:
    - name: {{SERVICE_NAME}}
      port: {{HTTP_PORT}}
      weight: 100
    timeouts:
      request: 10s
