# Prometheus Configuration for Enhanced Petstore Demo
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Enhanced Petstore Domain Service
  - job_name: 'petstore-domain'
    static_configs:
      - targets: ['petstore-domain:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Kafka metrics (if JMX exporter is enabled)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: '/metrics'

  # Redis metrics (if Redis exporter is enabled)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  # PostgreSQL metrics (if Postgres exporter is enabled)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

# Alerting rules for demo
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
