# Modern Marty Microservice Configuration Template
# Copy this file to config/services/{your_service_name}.yaml

# Database configuration - per service database
database:
  "{{SERVICE_NAME}}":
    host: "${{{SERVICE_NAME_UPPER}}_DB_HOST:-localhost}"
    port: ${{{SERVICE_NAME_UPPER}}_DB_PORT:-5432}
    database: "${{{SERVICE_NAME_UPPER}}_DB_NAME:-marty_{{SERVICE_NAME}}}"
    username: "${{{SERVICE_NAME_UPPER}}_DB_USER:-{{SERVICE_NAME}}_user}"
    password: "${{{SERVICE_NAME_UPPER}}_DB_PASSWORD:-change_me_in_production}"
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
    ssl_mode: "prefer"
    connection_timeout: 30

# Security configuration
security:
  grpc_tls:
    enabled: true
    mtls: true
    require_client_auth: true
    server_cert: "${TLS_SERVER_CERT:-/etc/tls/server/tls.crt}"
    server_key: "${TLS_SERVER_KEY:-/etc/tls/server/tls.key}"
    client_ca: "${TLS_CLIENT_CA:-/etc/tls/ca/ca.crt}"
    client_cert: "${TLS_CLIENT_CERT:-/etc/tls/client/tls.crt}"
    client_key: "${TLS_CLIENT_KEY:-/etc/tls/client/tls.key}"
    verify_hostname: true

  auth:
    required: true
    jwt_enabled: true
    jwt_algorithm: "HS256"
    jwt_secret: "${JWT_SECRET}"
    api_key_enabled: true
    client_cert_enabled: true
    extract_subject: true

  authz:
    enabled: true
    policy_config: "${AUTHZ_POLICY_CONFIG:-/etc/authz/policy.yaml}"
    default_action: "deny"

# Cryptographic configuration (if needed)
cryptographic:
  signing:
    algorithm: "rsa2048"
    key_id: "{{SERVICE_NAME}}-default"
    key_directory: "${KEY_DIRECTORY:-/app/data/keys}"
    key_rotation_days: 90
    certificate_validity_days: 365

  vault:
    url: "${VAULT_ADDR:-https://vault.internal:8200}"
    auth_method: "${VAULT_AUTH_METHOD:-approle}"
    token: "${VAULT_TOKEN:-}"
    role_id: "${VAULT_ROLE_ID:-}"
    secret_id: "${VAULT_SECRET_ID:-}"
    namespace: "${VAULT_NAMESPACE:-}"
    ca_cert: "${VAULT_CACERT:-/secrets/vault/ca.crt}"
    mount_path: "secret"

# Trust store configuration (if needed)
trust_store:
  trust_anchor:
    certificate_store_path: "${CERT_STORE_PATH:-/app/data/trust}"
    update_interval_hours: ${TRUST_UPDATE_INTERVAL:-24}
    validation_timeout_seconds: ${VALIDATION_TIMEOUT:-30}
    enable_online_verification: ${ENABLE_ONLINE_VERIFICATION:-false}

  pkd:
    service_url: "${PKD_SERVICE_URL:-http://pkd-service:8089}"
    enabled: ${PKD_ENABLED:-true}
    update_interval_hours: ${PKD_UPDATE_INTERVAL:-24}
    max_retries: ${PKD_MAX_RETRIES:-3}
    timeout_seconds: ${PKD_TIMEOUT:-30}

# Service discovery
service_discovery:
  hosts:
    csca_service: "${CSCA_SERVICE_HOST:-csca-service}"
    document_signer: "${DOCUMENT_SIGNER_HOST:-document-signer}"
    trust_anchor: "${TRUST_ANCHOR_HOST:-trust-anchor}"
    pkd_service: "${PKD_SERVICE_HOST:-pkd-service}"
    inspection_system: "${INSPECTION_SYSTEM_HOST:-inspection-system}"
  ports:
    csca_service: ${CSCA_SERVICE_PORT:-8081}
    document_signer: ${DOCUMENT_SIGNER_PORT:-8082}
    trust_anchor: ${TRUST_ANCHOR_PORT:-8080}
    pkd_service: ${PKD_SERVICE_PORT:-8089}
    inspection_system: ${INSPECTION_SYSTEM_PORT:-8083}
  enable_service_mesh: ${ENABLE_SERVICE_MESH:-false}
  service_mesh_namespace: "${SERVICE_MESH_NAMESPACE:-marty}"

# Logging configuration
logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers: ["console"]
  file: "${LOG_FILE:-}"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Monitoring configuration
monitoring:
  enabled: true
  metrics_port: ${METRICS_PORT:-9090}
  health_check_port: ${HEALTH_CHECK_PORT:-8080}
  prometheus_enabled: true
  tracing_enabled: true
  jaeger_endpoint: "${JAEGER_ENDPOINT:-http://jaeger:14268/api/traces}"
  service_name: "{{SERVICE_NAME}}"

# Resilience configuration
resilience:
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60
    half_open_max_calls: 3
  retry_policy:
    max_attempts: 3
    backoff_multiplier: 1.5
    max_delay_seconds: 30

# Service-specific configuration
services:
  "{{SERVICE_NAME}}":
    # Add your service-specific settings here
    max_concurrent_operations: 10
    operation_timeout_seconds: 30
    enable_caching: true
    cache_ttl_seconds: 3600

    # Enable event publishing if needed
    enable_event_publishing: true
    event_topics:
      - "{{SERVICE_NAME}}.operation.completed"
      - "{{SERVICE_NAME}}.error.occurred"
