apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    # Service mesh annotations
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    # Istio specific annotations
    traffic.sidecar.istio.io/includeInboundPorts: "50051,8080"
    # Linkerd specific annotations
    config.linkerd.io/skip-inbound-ports: "9000"
    # Marty platform annotations
    marty.io/service-type: grpc
    marty.io/load-balancer: enabled
spec:
  type: ClusterIP  # Use ClusterIP for internal services, LoadBalancer for external
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
    - name: http-health
      port: 8080
      targetPort: health
      protocol: TCP
    - name: metrics
      port: 9000
      targetPort: metrics
      protocol: TCP
  # Enhanced selector for Marty services
  selector:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: marty-platform
