apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  template:
    metadata:
      annotations:
        # Enhanced service mesh annotations
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "128Mi"
        sidecar.istio.io/logLevel: "info"
        # Linkerd proxy resource limits
        config.linkerd.io/proxy-cpu-limit: "100m"
        config.linkerd.io/proxy-memory-limit: "128Mi"
        config.linkerd.io/proxy-cpu-request: "10m"
        config.linkerd.io/proxy-memory-request: "64Mi"
        # Service mesh specific configs
        traffic.sidecar.istio.io/excludeOutboundPorts: "443,53"  # Exclude HTTPS and DNS
        config.linkerd.io/skip-outbound-ports: "443,53"
    spec:
      containers:
      - name: payment-service
        env:
        - name: SERVICE_MESH_ENABLED
          value: "true"
        - name: TELEMETRY_ENDPOINT
          value: "jaeger-collector.observability:14250"
        - name: METRICS_ENABLED
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
