"""Messaging system for reliable message passing and event handling."""

# Import from Domain Layer (contracts and interfaces)
# Import from bootstrap layer (concrete implementations)
from .bootstrap import (
    DLQHandler,
    DLQManager,
    EventStreamManager,
    JSONMessageSerializer,
    MemoryMessageBackend,
    MessageBus,
    MessageConsumer,
    MessageProducer,
    MessageQueue,
    MessageRouter,
    MessagingManager,
    MiddlewareChain,
    create_messaging_manager,
    setup_messaging_system,
)
from .domain.models import (
    BackendConfig,
    BackendType,
    ConsumerConfig,
    DLQConfig,
    DLQMessage,
    DLQPolicy,
    MatchType,
    Message,
    MessageHeaders,
    MessagePattern,
    MessagePriority,
    MessageStatus,
    MessagingConfig,
    MessagingConnectionError,
    MessagingError,
    MiddlewareStage,
    MiddlewareType,
    ProducerConfig,
    RetryConfig,
    RetryStrategy,
    RoutingConfig,
    RoutingRule,
    RoutingType,
)
from .domain.ports import (
    IDLQManager,
    IMessageBackend,
    IMessageConsumer,
    IMessageExchange,
    IMessageMiddleware,
    IMessageProducer,
    IMessageQueue,
    IMessageRouter,
    IMessageSerializer,
    IMessagingManager,
)

__all__ = [
    # Domain Layer - Interfaces and Contracts
    "BackendConfig",
    "BackendType",
    "ConsumerConfig",
    "DLQConfig",
    "DLQMessage",
    "DLQPolicy",
    "IDLQManager",
    "IMessageBackend",
    "IMessageConsumer",
    "IMessageExchange",
    "IMessageMiddleware",
    "IMessageProducer",
    "IMessageQueue",
    "IMessageRouter",
    "IMessageSerializer",
    "IMessagingManager",
    "Message",
    "MessageHeaders",
    "MessagePattern",
    "MessagePriority",
    "MessageStatus",
    "MessagingConfig",
    "MessagingConnectionError",
    "MessagingError",
    "MiddlewareStage",
    "MiddlewareType",
    "ProducerConfig",
    "RoutingConfig",
    "RoutingRule",
    "RoutingType",
    "MatchType",
    "RetryConfig",
    "RetryStrategy",
    # Bootstrap Layer - Concrete Implementations
    "DLQHandler",
    "DLQManager",
    "EventStreamManager",
    "JSONMessageSerializer",
    "MemoryMessageBackend",
    "MessageBus",
    "MessageConsumer",
    "MessageProducer",
    "MessageQueue",
    "MessageRouter",
    "MessagingManager",
    "MiddlewareChain",
    "create_messaging_manager",
    "setup_messaging_system",
]
