[package]
name = "mmf"
description = "Facade crate for the Rust Marty Microservices Framework"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
mmf-config.workspace = true
mmf-core.workspace = true
mmf-messaging.workspace = true
mmf-observability.workspace = true
mmf-platform.workspace = true
mmf-resilience.workspace = true
mmf-runtime.workspace = true
mmf-security.workspace = true

[lints]
workspace = true
